<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>XO.Console.Cli</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.3" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.6.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.2" />
    <PackageReference Include="Verify" Version="31.16.2" />
    <PackageReference Include="Verify.SourceGenerators" Version="2.5.0" />
    <PackageReference Include="Verify.XunitV3" Version="31.16.2" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XO.Console.Cli.Analyzers\XO.Console.Cli.Analyzers.csproj" />
    <ProjectReference Include="..\XO.Console.Cli\XO.Console.Cli.csproj" />
  </ItemGroup>

</Project>
