<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <RootNamespace>XO.Console.Cli</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.6.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.2" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XO.Console.Cli.Analyzers\XO.Console.Cli.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\XO.Console.Cli.Extensions\XO.Console.Cli.Extensions.csproj" />
    <ProjectReference Include="..\XO.Console.Cli.Instrumentation\XO.Console.Cli.Instrumentation.csproj" />
    <ProjectReference Include="..\XO.Console.Cli\XO.Console.Cli.csproj" />
  </ItemGroup>

</Project>
