//HintName: CommandBuilderFactory.g.cs
// <auto-generated/>
using System;
using XO.Console.Cli;
using XO.Console.Cli.Infrastructure;

#nullable enable

namespace XO.Console.Cli.Generated;

/// <summary>
/// This class was auto-generated to support the <c>XO.Console.Cli</c> infrastructure. It is not intended to be used directly from your code.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("XO.Console.Cli.Analyzers", "5.0.0.0")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
internal sealed class CommandBuilderFactory : ICommandBuilderFactory
{
#pragma warning disable CS0436 // Type conflicts with imported type
    public static readonly CommandBuilderFactory Instance = new CommandBuilderFactory();
#pragma warning restore CS0436 // Type conflicts with imported type

    public void ConfigureCommandApp(ICommandAppBuilder builder)
    {
        builder.AddBranch("group", builder => {
            builder.AddBranch("get", builder => {
                builder.AddCommand<Test.Command3>("command");
            });
            builder.AddBranch("load", builder => {
                builder.AddCommand<Test.Command2>("command2", builder => {
                    builder.SetDescription("Does something else?");
                });
                builder.AddCommand<Test.Command1>("command1", builder => {
                    builder.AddAlias("command");
                    builder.SetDescription("Does something?");
                });
            });
        });
    }

    public CommandBuilder? CreateCommandBuilder<TCommand>(string verb)
        where TCommand : class, ICommand
    {
        if (typeof(TCommand) == typeof(Test.Command1))
        {
            return new CommandBuilder(
                verb,
                static (resolver) => resolver.Get<Test.Command1>(),
                typeof(XO.Console.Cli.CommandParameters));
        }
        if (typeof(TCommand) == typeof(Test.Command2))
        {
            return new CommandBuilder(
                verb,
                static (resolver) => resolver.Get<Test.Command2>(),
                typeof(XO.Console.Cli.CommandParameters));
        }
        if (typeof(TCommand) == typeof(Test.Command3))
        {
            return new CommandBuilder(
                verb,
                static (resolver) => resolver.Get<Test.Command3>(),
                typeof(XO.Console.Cli.CommandParameters));
        }
        return null;
    }

    [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
    internal static void Register()
    {
        TypeRegistry.RegisterCommandBuilderFactory(Instance);
    }
}
