//HintName: CommandParametersFactory.g.cs
// <auto-generated/>
using System;
using System.Collections.Immutable;
using XO.Console.Cli;
using XO.Console.Cli.Infrastructure;
using XO.Console.Cli.Model;
using static XO.Console.Cli.Infrastructure.ParameterValueConverter;

#nullable enable

namespace XO.Console.Cli.Generated;

/// <summary>
/// This class was auto-generated to support the <c>XO.Console.Cli</c> infrastructure. It is not intended to be used directly from your code.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("XO.Console.Cli.Analyzers", "5.0.0.0")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
internal sealed class CommandParametersFactory : ICommandParametersFactory
{
#pragma warning disable CS0436 // Type conflicts with imported type
    public static readonly CommandParametersFactory Instance = new CommandParametersFactory();
#pragma warning restore CS0436 // Type conflicts with imported type

    public CommandParametersInfo? DescribeParameters(Type parametersType)
    {
        if (parametersType is null)
            throw new ArgumentNullException(nameof(parametersType));

        if (parametersType == typeof(Test.Parameters))
        {
            return new CommandParametersInfo(
                ImmutableArray<CommandArgument>.Empty,
                ImmutableArray.Create<CommandOption>(
                    new CommandOption(
                        "--value",
                        static (context, values, converters) => ((Test.Parameters)context.Parameters).Constructor = ConvertSingle<Test.MyType>(values, converters, static (value) => new Test.MyType(value)),
                        typeof(Test.MyType),
                        null)
                    {
                        Aliases = ImmutableArray.Create<string>(),
                        IsFlag = false,
                        IsHidden = false,
                    },
                    new CommandOption(
                        "--count",
                        static (context, values, converters) => ((Test.Parameters)context.Parameters).Parse = ConvertSingle<System.Int32>(values, converters, static (value) => System.Int32.Parse(value)),
                        typeof(System.Int32),
                        null)
                    {
                        Aliases = ImmutableArray.Create<string>(),
                        IsFlag = false,
                        IsHidden = false,
                    },
                    new CommandOption(
                        "--style",
                        static (context, values, converters) => ((Test.Parameters)context.Parameters).Enum = ConvertSingle<XO.Console.Cli.CommandOptionStyle>(values, converters, ParseEnum<XO.Console.Cli.CommandOptionStyle>),
                        typeof(XO.Console.Cli.CommandOptionStyle),
                        null)
                    {
                        Aliases = ImmutableArray.Create<string>(),
                        IsFlag = false,
                        IsHidden = false,
                    },
                    new CommandOption(
                        "--command",
                        static (context, values, converters) => ((Test.Parameters)context.Parameters).None = ConvertSingle<XO.Console.Cli.Command>(values, converters, ParseNone<XO.Console.Cli.Command>),
                        typeof(XO.Console.Cli.Command),
                        null)
                    {
                        Aliases = ImmutableArray.Create<string>(),
                        IsFlag = false,
                        IsHidden = false,
                    },
                    new CommandOption(
                        "--name",
                        static (context, values, converters) => ((Test.Parameters)context.Parameters).String = ConvertSingle<System.String>(values, converters, static (value) => value),
                        typeof(System.String),
                        null)
                    {
                        Aliases = ImmutableArray.Create<string>(),
                        IsFlag = false,
                        IsHidden = false,
                    },
                    new CommandOption(
                        "--code",
                        static (context, values, converters) => ((Test.Parameters)context.Parameters).Char = ConvertSingle<System.Char>(values, converters, ParseChar),
                        typeof(System.Char),
                        null)
                    {
                        Aliases = ImmutableArray.Create<string>(),
                        IsFlag = false,
                        IsHidden = false,
                    }));
        }

        return null;
    }

    [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
    internal static void Register()
    {
        TypeRegistry.RegisterCommandParametersFactory(Instance);
    }
}
